cluster.name: LiferayElasticsearchCluster
node.name: es-node1
network.host: 0.0.0.0
discovery.type: single-node

# Enable Elastic security + TLS with a FIPS-approved cipher suite list
xpack.security.enabled: true
xpack.security.fips_mode.enabled: true

xpack.security.http.ssl:
  enabled: true
  verification_mode: certificate
  key: certs/elastic-node.key
  certificate: certs/elastic-node.crt
  certificate_authorities: [ "certs/elastic-ca.crt" ]
  supported_protocols: [ "TLSv1.2" ]
  cipher_suites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  key: certs/elastic-node.key
  certificate: certs/elastic-node.crt
  certificate_authorities: [ "certs/elastic-ca.crt" ]
  supported_protocols: [ "TLSv1.2" ]
  cipher_suites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

xpack.license.self_generated.type: trial

action.destructive_requires_name: true
