services:

  database:
    image: liferay-fips/mysql:8.0.43-fips
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        MYSQL_BASE_IMAGE: ${MYSQL_BASE_IMAGE:-mysql:8.0}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: lportal
    command: mysqld
    ports:
      - "3307:3306"
    volumes:
      - mysql-fips-data:/var/lib/mysql

  liferay:
    user: root:root
    build: ./liferay/
    ports:
      - "8081:8080"
      - "11312:11311"
      - "8001:8000"
    depends_on:
      - database
      - search

  search:
    image: liferay-fips/elasticsearch:8.17.2-fips
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
      args:
        ELASTIC_BASE_IMAGE: ${ELASTIC_BASE_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch:8.17.2}
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-elasticFips!2024}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

volumes:
  elastic-data:
  mysql-fips-data:
    driver: local